version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: myuon/portals-me-account-ci:latest
    steps:
      - checkout
      - run: npm i -g yarn
      - run: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/workspace
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/install
      - run: curl -fsSL https://get.pulumi.com | sh
      - run: ~/.pulumi/bin/pulumi stack select stg
      - run: ~/.pulumi/bin/pulumi up -y

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          context: aws
