version: 2.1

orbs:
  pulumi: pulumi/pulumi@1.0.0

jobs:
  install:
    working_directory: ~/workspace
    docker:
      - image: myuon/portals-me-account-ci:latest
    steps:
      - checkout
      - run: npm i -g yarn
      - run: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/workspace
    docker:
      - image: myuon/portals-me-account-ci:latest
    steps:
      - attach_workspace:
          at: .
      - run: export STACK_NAME=myuon/portals-me-account/$(date +%s)
      - run: pulumi stack init ${STACK_NAME}
      - run: pulumi stack select ${STACK_NAME}
      - run: pulumi config set aws:region ap-northeast-1
      - run: pulumi up -y
      - run: ENV=$(pulumi stack output output) yarn test
      - run: export BUILD_STATUS="$?"
      - run: pulumi destroy -y && pulumi stack rm -y
      - run: exit ${BUILD_STATUS}
  deploy:
    working_directory: ~/workspace
    docker:
      - image: myuon/portals-me-account-ci:latest
    steps:
      - attach_workspace:
          at: .
      - run: pulumi stack select myuon/portals-me-account/stg
      - run: pulumi config set aws:region ap-northeast-1
      - run: pulumi up -y

workflows:
  version: 2
  deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - install
            - test
          context: aws
